name: Jobs test
on: push
jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: get-repo-code
        uses: actions/checkout@v4
      - name: Validate html file
        run: test -f index.html

  validate-js:
    runs-on: ubuntu-latest
    steps:
      - name: get-repo-code
        uses: actions/checkout@v4
      - name: Validate js file
        run: test -f script.js

  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: get-repo-code
        uses: actions/checkout@v4

      - name: Validate js code
        run: test -f script.js

      - name: Validate HTML code
        run: npx htmlhint index.html            